AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

# ~~~ Layout ~~~
Layout/HashAlignment:
  Include:
    - 'lib/**/*.rb'
Layout/LineLength:
  Include:
    - 'lib/**/*.rb'
# ~~~ Lint ~~~
# ~~~ Metrics ~~~
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 16
# ~~~ Naming ~~~
Naming/VariableNumber:
  EnforcedStyle: snake_case
# ~~~ Style ~~~
Style/AccessorGrouping:
  Enabled: false # for yard
Style/BisectedAttrAccessor:
  Enabled: false # for yard
Style/FormatStringToken:
  Enabled: false # https://github.com/rubocop-hq/rubocop/issues/7944
Style/RedundantReturn:
  Enabled: false

